#!/usr/bin/env python
# -*- coding: utf-8 -*-

# Copyright © 2013, IOhannes m zmölnig, IEM

# This file is part of WILMix
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with WILMix.  If not, see <http://www.gnu.org/licenses/>.
import os,sys

LIBDIR='/usr/lib'
dir = os.path.dirname(os.path.abspath(__file__))
if os.path.exists(os.path.join(dir, '.git')) or \
       os.path.exists(os.path.join(dir, '..', '.git')):
        root = os.path.split(dir)[0]
else:
       root = os.path.join(LIBDIR, 'WILMA', 'python')
sys.path.insert(0, root)


## cmdline arguments
import argparse
parser = argparse.ArgumentParser()
parser.add_argument("--logfile", type=str,
                    help="Logfile to write to")
args = parser.parse_args()


import logging
import gobject
from WILMA import SMi, logger

if __name__ == '__main__':
    if args.logfile is None:
	    args.logfile='stderr'
    l = logger.logger(args.logfile)
    logging.info("SM...")
    gobject.threads_init()
    sm = SMi()
    import time

    try:
        gobject.MainLoop().run()
    except KeyboardInterrupt:
        logging.exception("WILMAsm KeyboardInterrupt")
        pass
    sm.cleanup()


