# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SMconfig.ui'
#
# Created: Mon Mar 25 18:21:35 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_SMconfig(object):
    def setupUi(self, SMconfig):
        SMconfig.setObjectName("SMconfig")
        SMconfig.resize(624, 374)
        SMconfig.setModal(True)
        self.closeButtons = QtGui.QDialogButtonBox(SMconfig)
        self.closeButtons.setGeometry(QtCore.QRect(390, 330, 221, 39))
        self.closeButtons.setOrientation(QtCore.Qt.Horizontal)
        self.closeButtons.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.closeButtons.setObjectName("closeButtons")
        self.copyConfigButton = QtGui.QPushButton(SMconfig)
        self.copyConfigButton.setGeometry(QtCore.QRect(10, 340, 181, 23))
        self.copyConfigButton.setObjectName("copyConfigButton")
        self.frame_FileSync = QtGui.QGroupBox(SMconfig)
        self.frame_FileSync.setGeometry(QtCore.QRect(370, 190, 251, 141))
        self.frame_FileSync.setObjectName("frame_FileSync")
        self.frame_FilePull = QtGui.QGroupBox(self.frame_FileSync)
        self.frame_FilePull.setGeometry(QtCore.QRect(10, 20, 231, 51))
        self.frame_FilePull.setObjectName("frame_FilePull")
        self.pullDirButton = QtGui.QToolButton(self.frame_FilePull)
        self.pullDirButton.setGeometry(QtCore.QRect(170, 20, 24, 20))
        self.pullDirButton.setObjectName("pullDirButton")
        self.pullDir = QtGui.QLabel(self.frame_FilePull)
        self.pullDir.setGeometry(QtCore.QRect(10, 20, 151, 16))
        self.pullDir.setObjectName("pullDir")
        self.pullButton = QtGui.QCommandLinkButton(self.frame_FilePull)
        self.pullButton.setGeometry(QtCore.QRect(200, 10, 31, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pullButton.sizePolicy().hasHeightForWidth())
        self.pullButton.setSizePolicy(sizePolicy)
        self.pullButton.setText("")
        self.pullButton.setObjectName("pullButton")
        self.frame_FilePush = QtGui.QGroupBox(self.frame_FileSync)
        self.frame_FilePush.setGeometry(QtCore.QRect(10, 80, 231, 51))
        self.frame_FilePush.setObjectName("frame_FilePush")
        self.pushDirButton = QtGui.QToolButton(self.frame_FilePush)
        self.pushDirButton.setGeometry(QtCore.QRect(170, 19, 24, 20))
        self.pushDirButton.setObjectName("pushDirButton")
        self.pushDir = QtGui.QLabel(self.frame_FilePush)
        self.pushDir.setGeometry(QtCore.QRect(10, 20, 151, 16))
        self.pushDir.setObjectName("pushDir")
        self.pushButton = QtGui.QCommandLinkButton(self.frame_FilePush)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(200, 10, 31, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.frame_Audio = QtGui.QGroupBox(SMconfig)
        self.frame_Audio.setGeometry(QtCore.QRect(10, 10, 141, 321))
        self.frame_Audio.setObjectName("frame_Audio")
        self.gainFader = QtGui.QSlider(self.frame_Audio)
        self.gainFader.setGeometry(QtCore.QRect(10, 20, 16, 291))
        self.gainFader.setOrientation(QtCore.Qt.Vertical)
        self.gainFader.setObjectName("gainFader")
        self.meters = qsynthMeter(self.frame_Audio)
        self.meters.setGeometry(QtCore.QRect(30, 20, 101, 291))
        self.meters.setObjectName("meters")
        self.groupBox = QtGui.QGroupBox(SMconfig)
        self.groupBox.setGeometry(QtCore.QRect(160, 200, 201, 131))
        self.groupBox.setObjectName("groupBox")
        self.statemeter = statemeter(self.groupBox)
        self.statemeter.setGeometry(QtCore.QRect(10, 20, 181, 101))
        self.statemeter.setObjectName("statemeter")
        self.frame_Mode = QtGui.QWidget(SMconfig)
        self.frame_Mode.setGeometry(QtCore.QRect(150, 10, 211, 181))
        self.frame_Mode.setObjectName("frame_Mode")
        self.frame_StreamSettings = QtGui.QGroupBox(self.frame_Mode)
        self.frame_StreamSettings.setGeometry(QtCore.QRect(10, 60, 191, 121))
        self.frame_StreamSettings.setObjectName("frame_StreamSettings")
        self.streamProtocol = QtGui.QComboBox(self.frame_StreamSettings)
        self.streamProtocol.setGeometry(QtCore.QRect(100, 20, 81, 22))
        self.streamProtocol.setObjectName("streamProtocol")
        self.streamProtocol.addItem("")
        self.label_streamProtocol = QtGui.QLabel(self.frame_StreamSettings)
        self.label_streamProtocol.setGeometry(QtCore.QRect(10, 20, 52, 22))
        self.label_streamProtocol.setObjectName("label_streamProtocol")
        self.label_streamProfile = QtGui.QLabel(self.frame_StreamSettings)
        self.label_streamProfile.setGeometry(QtCore.QRect(10, 50, 52, 22))
        self.label_streamProfile.setObjectName("label_streamProfile")
        self.label_streamChannels = QtGui.QLabel(self.frame_StreamSettings)
        self.label_streamChannels.setGeometry(QtCore.QRect(10, 80, 52, 22))
        self.label_streamChannels.setObjectName("label_streamChannels")
        self.streamChannels = QtGui.QSpinBox(self.frame_StreamSettings)
        self.streamChannels.setGeometry(QtCore.QRect(130, 80, 50, 22))
        self.streamChannels.setMinimum(4)
        self.streamChannels.setMaximum(4)
        self.streamChannels.setObjectName("streamChannels")
        self.streamProfile = QtGui.QComboBox(self.frame_StreamSettings)
        self.streamProfile.setGeometry(QtCore.QRect(100, 50, 81, 22))
        self.streamProfile.setObjectName("streamProfile")
        self.streamProfile.addItem("")
        self.modeSelector = QtGui.QComboBox(self.frame_Mode)
        self.modeSelector.setGeometry(QtCore.QRect(90, 20, 110, 22))
        self.modeSelector.setObjectName("modeSelector")
        self.modeSelector.addItem("")
        self.modeSelector.addItem("")
        self.modeSelector.addItem("")
        self.label_mode = QtGui.QLabel(self.frame_Mode)
        self.label_mode.setGeometry(QtCore.QRect(20, 20, 52, 13))
        self.label_mode.setObjectName("label_mode")
        self.frame_Network = QtGui.QGroupBox(SMconfig)
        self.frame_Network.setGeometry(QtCore.QRect(360, 10, 261, 51))
        self.frame_Network.setObjectName("frame_Network")
        self.networkInterface = QtGui.QComboBox(self.frame_Network)
        self.networkInterface.setGeometry(QtCore.QRect(150, 20, 101, 22))
        self.networkInterface.setObjectName("networkInterface")
        self.networkInterface.addItem("")
        self.networkInterface.addItem("")
        self.label_networkInterface = QtGui.QLabel(self.frame_Network)
        self.label_networkInterface.setGeometry(QtCore.QRect(10, 20, 52, 13))
        self.label_networkInterface.setObjectName("label_networkInterface")

        self.retranslateUi(SMconfig)

    def retranslateUi(self, SMconfig):
        SMconfig.setWindowTitle(QtGui.QApplication.translate("SMconfig", "Configuration of ...", None, QtGui.QApplication.UnicodeUTF8))
        self.copyConfigButton.setText(QtGui.QApplication.translate("SMconfig", "Copy to selected SMi\'s", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_FileSync.setTitle(QtGui.QApplication.translate("SMconfig", "FileSync", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_FilePull.setTitle(QtGui.QApplication.translate("SMconfig", "Pull data from SMi", None, QtGui.QApplication.UnicodeUTF8))
        self.pullDirButton.setText(QtGui.QApplication.translate("SMconfig", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.pullDir.setText(QtGui.QApplication.translate("SMconfig", "<Destination Folder>", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_FilePush.setTitle(QtGui.QApplication.translate("SMconfig", "Push data to SMi", None, QtGui.QApplication.UnicodeUTF8))
        self.pushDirButton.setText(QtGui.QApplication.translate("SMconfig", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushDir.setText(QtGui.QApplication.translate("SMconfig", "<Source folder>", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_Audio.setTitle(QtGui.QApplication.translate("SMconfig", "Audio", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("SMconfig", "System Health", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_StreamSettings.setTitle(QtGui.QApplication.translate("SMconfig", "Stream Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.streamProtocol.setItemText(0, QtGui.QApplication.translate("SMconfig", "RTP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_streamProtocol.setText(QtGui.QApplication.translate("SMconfig", "Protocol", None, QtGui.QApplication.UnicodeUTF8))
        self.label_streamProfile.setText(QtGui.QApplication.translate("SMconfig", "Profile", None, QtGui.QApplication.UnicodeUTF8))
        self.label_streamChannels.setText(QtGui.QApplication.translate("SMconfig", "Channels", None, QtGui.QApplication.UnicodeUTF8))
        self.streamProfile.setItemText(0, QtGui.QApplication.translate("SMconfig", "L16", None, QtGui.QApplication.UnicodeUTF8))
        self.modeSelector.setItemText(0, QtGui.QApplication.translate("SMconfig", "Streaming", None, QtGui.QApplication.UnicodeUTF8))
        self.modeSelector.setItemText(1, QtGui.QApplication.translate("SMconfig", "Recording", None, QtGui.QApplication.UnicodeUTF8))
        self.modeSelector.setItemText(2, QtGui.QApplication.translate("SMconfig", "Processing", None, QtGui.QApplication.UnicodeUTF8))
        self.label_mode.setText(QtGui.QApplication.translate("SMconfig", "Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_Network.setTitle(QtGui.QApplication.translate("SMconfig", "Network", None, QtGui.QApplication.UnicodeUTF8))
        self.networkInterface.setItemText(0, QtGui.QApplication.translate("SMconfig", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.networkInterface.setItemText(1, QtGui.QApplication.translate("SMconfig", "wlan0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_networkInterface.setText(QtGui.QApplication.translate("SMconfig", "Interface", None, QtGui.QApplication.UnicodeUTF8))

from qsynthMeter import qsynthMeter
from statemeter import statemeter
