# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SMconfig.ui'
#
# Created: Wed Mar 27 21:41:21 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_SMconfig(object):
    def setupUi(self, SMconfig):
        SMconfig.setObjectName("SMconfig")
        SMconfig.resize(581, 329)
        SMconfig.setModal(True)
        self.closeButtons = QtGui.QDialogButtonBox(SMconfig)
        self.closeButtons.setGeometry(QtCore.QRect(350, 290, 221, 39))
        self.closeButtons.setOrientation(QtCore.Qt.Horizontal)
        self.closeButtons.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.closeButtons.setObjectName("closeButtons")
        self.copyConfigButton = QtGui.QPushButton(SMconfig)
        self.copyConfigButton.setGeometry(QtCore.QRect(10, 300, 181, 23))
        self.copyConfigButton.setObjectName("copyConfigButton")
        self.frame_FileSync = QtGui.QGroupBox(SMconfig)
        self.frame_FileSync.setGeometry(QtCore.QRect(160, 200, 201, 91))
        self.frame_FileSync.setObjectName("frame_FileSync")
        self.pullButton = QtGui.QCommandLinkButton(self.frame_FileSync)
        self.pullButton.setGeometry(QtCore.QRect(10, 20, 181, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pullButton.sizePolicy().hasHeightForWidth())
        self.pullButton.setSizePolicy(sizePolicy)
        self.pullButton.setObjectName("pullButton")
        self.pushButton = QtGui.QCommandLinkButton(self.frame_FileSync)
        self.pushButton.setEnabled(True)
        self.pushButton.setGeometry(QtCore.QRect(10, 50, 181, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.frame_Audio = QtGui.QGroupBox(SMconfig)
        self.frame_Audio.setGeometry(QtCore.QRect(10, 10, 141, 281))
        self.frame_Audio.setObjectName("frame_Audio")
        self.gainFader = QtGui.QSlider(self.frame_Audio)
        self.gainFader.setGeometry(QtCore.QRect(10, 20, 16, 251))
        self.gainFader.setOrientation(QtCore.Qt.Vertical)
        self.gainFader.setObjectName("gainFader")
        self.meter = qsynthMeter(self.frame_Audio)
        self.meter.setGeometry(QtCore.QRect(30, 20, 101, 251))
        self.meter.setObjectName("meter")
        self.frame_state = QtGui.QGroupBox(SMconfig)
        self.frame_state.setGeometry(QtCore.QRect(160, 60, 201, 131))
        self.frame_state.setObjectName("frame_state")
        self.statemeter = statemeter(self.frame_state)
        self.statemeter.setGeometry(QtCore.QRect(10, 20, 181, 81))
        self.statemeter.setObjectName("statemeter")
        self.label_timestamp = QtGui.QLabel(self.frame_state)
        self.label_timestamp.setGeometry(QtCore.QRect(20, 100, 71, 16))
        self.label_timestamp.setObjectName("label_timestamp")
        self.timestamp = QtGui.QLineEdit(self.frame_state)
        self.timestamp.setGeometry(QtCore.QRect(110, 100, 81, 20))
        self.timestamp.setFrame(True)
        self.timestamp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timestamp.setReadOnly(True)
        self.timestamp.setPlaceholderText("")
        self.timestamp.setObjectName("timestamp")
        self.frame_Mode = QtGui.QWidget(SMconfig)
        self.frame_Mode.setGeometry(QtCore.QRect(370, 20, 211, 181))
        self.frame_Mode.setObjectName("frame_Mode")
        self.modeSelector = QtGui.QComboBox(self.frame_Mode)
        self.modeSelector.setGeometry(QtCore.QRect(90, 20, 110, 22))
        self.modeSelector.setObjectName("modeSelector")
        self.modeSelector.addItem("")
        self.modeSelector.addItem("")
        self.modeSelector.addItem("")
        self.label_mode = QtGui.QLabel(self.frame_Mode)
        self.label_mode.setGeometry(QtCore.QRect(20, 20, 52, 13))
        self.label_mode.setObjectName("label_mode")
        self.frame_StreamSettings = QtGui.QGroupBox(self.frame_Mode)
        self.frame_StreamSettings.setGeometry(QtCore.QRect(10, 50, 191, 121))
        self.frame_StreamSettings.setObjectName("frame_StreamSettings")
        self.streamProtocol = QtGui.QComboBox(self.frame_StreamSettings)
        self.streamProtocol.setGeometry(QtCore.QRect(100, 20, 81, 22))
        self.streamProtocol.setObjectName("streamProtocol")
        self.streamProtocol.addItem("")
        self.label_streamProtocol = QtGui.QLabel(self.frame_StreamSettings)
        self.label_streamProtocol.setGeometry(QtCore.QRect(10, 20, 52, 22))
        self.label_streamProtocol.setObjectName("label_streamProtocol")
        self.label_streamProfile = QtGui.QLabel(self.frame_StreamSettings)
        self.label_streamProfile.setGeometry(QtCore.QRect(10, 50, 52, 22))
        self.label_streamProfile.setObjectName("label_streamProfile")
        self.label_streamChannels = QtGui.QLabel(self.frame_StreamSettings)
        self.label_streamChannels.setGeometry(QtCore.QRect(10, 80, 52, 22))
        self.label_streamChannels.setObjectName("label_streamChannels")
        self.streamChannels = QtGui.QSpinBox(self.frame_StreamSettings)
        self.streamChannels.setGeometry(QtCore.QRect(130, 80, 50, 22))
        self.streamChannels.setMinimum(4)
        self.streamChannels.setMaximum(4)
        self.streamChannels.setObjectName("streamChannels")
        self.streamProfile = QtGui.QComboBox(self.frame_StreamSettings)
        self.streamProfile.setGeometry(QtCore.QRect(100, 50, 81, 22))
        self.streamProfile.setObjectName("streamProfile")
        self.streamProfile.addItem("")
        self.frame_Network = QtGui.QGroupBox(SMconfig)
        self.frame_Network.setGeometry(QtCore.QRect(160, 10, 201, 51))
        self.frame_Network.setObjectName("frame_Network")
        self.networkInterface = QtGui.QComboBox(self.frame_Network)
        self.networkInterface.setGeometry(QtCore.QRect(90, 20, 101, 22))
        self.networkInterface.setObjectName("networkInterface")
        self.networkInterface.addItem("")
        self.networkInterface.addItem("")
        self.label_networkInterface = QtGui.QLabel(self.frame_Network)
        self.label_networkInterface.setGeometry(QtCore.QRect(10, 20, 52, 13))
        self.label_networkInterface.setObjectName("label_networkInterface")

        self.retranslateUi(SMconfig)

    def retranslateUi(self, SMconfig):
        SMconfig.setWindowTitle(QtGui.QApplication.translate("SMconfig", "Configuration of ...", None, QtGui.QApplication.UnicodeUTF8))
        self.copyConfigButton.setText(QtGui.QApplication.translate("SMconfig", "Copy to selected SMi\'s", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_FileSync.setTitle(QtGui.QApplication.translate("SMconfig", "FileSync", None, QtGui.QApplication.UnicodeUTF8))
        self.pullButton.setText(QtGui.QApplication.translate("SMconfig", "Pull data from SMi", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("SMconfig", "Push data to SMi", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_Audio.setTitle(QtGui.QApplication.translate("SMconfig", "Audio", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_state.setTitle(QtGui.QApplication.translate("SMconfig", "System Health", None, QtGui.QApplication.UnicodeUTF8))
        self.label_timestamp.setText(QtGui.QApplication.translate("SMconfig", "TimeStamp", None, QtGui.QApplication.UnicodeUTF8))
        self.modeSelector.setItemText(0, QtGui.QApplication.translate("SMconfig", "Streaming", None, QtGui.QApplication.UnicodeUTF8))
        self.modeSelector.setItemText(1, QtGui.QApplication.translate("SMconfig", "Recording", None, QtGui.QApplication.UnicodeUTF8))
        self.modeSelector.setItemText(2, QtGui.QApplication.translate("SMconfig", "Processing", None, QtGui.QApplication.UnicodeUTF8))
        self.label_mode.setText(QtGui.QApplication.translate("SMconfig", "Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_StreamSettings.setTitle(QtGui.QApplication.translate("SMconfig", "Stream Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.streamProtocol.setItemText(0, QtGui.QApplication.translate("SMconfig", "RTP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_streamProtocol.setText(QtGui.QApplication.translate("SMconfig", "Protocol", None, QtGui.QApplication.UnicodeUTF8))
        self.label_streamProfile.setText(QtGui.QApplication.translate("SMconfig", "Profile", None, QtGui.QApplication.UnicodeUTF8))
        self.label_streamChannels.setText(QtGui.QApplication.translate("SMconfig", "Channels", None, QtGui.QApplication.UnicodeUTF8))
        self.streamProfile.setItemText(0, QtGui.QApplication.translate("SMconfig", "L16", None, QtGui.QApplication.UnicodeUTF8))
        self.frame_Network.setTitle(QtGui.QApplication.translate("SMconfig", "Network", None, QtGui.QApplication.UnicodeUTF8))
        self.networkInterface.setItemText(0, QtGui.QApplication.translate("SMconfig", "eth0", None, QtGui.QApplication.UnicodeUTF8))
        self.networkInterface.setItemText(1, QtGui.QApplication.translate("SMconfig", "wlan0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_networkInterface.setText(QtGui.QApplication.translate("SMconfig", "Interface", None, QtGui.QApplication.UnicodeUTF8))

from qsynthMeter import qsynthMeter
from statemeter import statemeter
